# Generated by Django 5.0 on 2023-12-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('duration', models.DurationField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('client', models.CharField(max_length=100, null=True)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='clientmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('payment', models.IntegerField(null=True)),
                ('method', models.CharField(max_length=50, null=True)),
                ('due', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectmodel')),
            ],
        ),
    ]
