# Generated by Django 5.0 on 2023-12-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projectmodel_clientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
