# Generated by Django 5.0 on 2023-12-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employeemodel_end_date_employeemodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
