# Generated by Django 5.0 on 2023-12-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employeemodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='occupation',
            field=models.CharField(choices=[('web dev', 'Web developer'), ('android dev', 'Android developer'), ('ios dev', 'IOS developer')], default='Web developer', max_length=50),
        ),
    ]
