# Generated by Django 5.0 on 2023-12-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employeemodel_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectmodel'),
        ),
    ]
